estoque = {
    "papel higienico": 30,
    "detergente": 15,
    "sabao em po": 20,
    "amaciante": 18,
    "esponja de prato": 25,
    "saco de lixo": 40,
    "creme dental": 22,
    "escova de dente": 35,
    "shampoo": 27,
    "condicionador": 26,
    "sabonete": 50,
    "desodorante": 19,
    "lamina de barbear": 12,
    "limpador sanitario": 17,
    "limpador de piso": 14,
    "papel toalha": 28,
    "papel aluminio": 13,
    "filme plastico": 11,
    "agua mineral": 60,
    "salgadinho": 45,
    "arroz": 55,
    "feijao": 43,
    "acucar": 38,
    "sal": 29,
    "oleo de soja": 34,
    "farinha de trigo": 31,
    "macarrao": 27,
    "molho de tomate": 36,
    "ervilha": 20,
    "milho verde": 22,
    "atum": 17,
    "sardinha": 16,
    "cafe": 39,
    "cha": 24,
    "achocolatado": 21,
    "leite em po": 18,
    "leite longa vida": 42,
    "biscoito doce": 44,
    "biscoito salgado": 33,
    "bolacha recheada": 28,
    "margarina": 19,
    "manteiga": 14,
    "iogurte": 23,
    "refrigerante": 50,
    "suco": 37,
    "agua com gas": 26,
    "carne bovina": 30,
    "frango congelado": 34,
    "linguica": 21,
    "presunto": 25,
    "queijo": 29,
    "ovo": 60,
    "pao de forma": 32,
    "pao frances": 40,
    "massa para pizza": 15,
    "pizza congelada": 10,
    "hamburguer congelado": 18,
    "batata congelada": 22,
    "sorvete": 20,
    "picole": 17,
    "gelatina": 13,
    "pudim": 12,
    "mistura para bolo": 14,
    "fermento em po": 9,
    "baunilha": 5,
    "canela em po": 8,
    "tempero pronto": 16,
    "caldo de galinha": 19,
    "vinagre": 23,
    "molho shoyu": 11,
    "ketchup": 26,
    "mostarda": 21,
    "maionese": 20,
    "azeite": 18,
    "massa de tomate": 15,
    "creme de leite": 24,
    "leite condensado": 28,
    "milho para pipoca": 17,
    "pipoca de microondas": 22,
    "granola": 9,
    "cereal matinal": 16,
    "barra de cereal": 12,
    "frutas cristalizadas": 7,
    "castanha de caju": 6,
    "nozes": 5,
    "amendoim": 13,
    "uva passa": 10,
    "gel antisseptico": 30,
    "alcool em gel": 40,
    "mascara descartavel": 45,
    "luva descartavel": 35,
    "sabao liquido": 20,
    "esponja de aco": 18,
    "desinfetante": 25,
    "multiuso": 19,
    "sabao em barra": 23,
    "vela": 0,
    "fosforo": 12,
    "isqueiro": 10,
    "pilha": 17,
    "papel filme": 11
}


print("!--------------------------- Mercado Fazueli ---------------------------!")
action = input("Qual item deseja saber a quantidade em estoque: ")

if estoque[action] <= 0:
    print("Não possui esse item em estoque")

elif estoque[action] > 0:
    print(f"{action} existe em estoque com {estoque[action]} disponiveis")