dicionario = {
"apple": "maçã",
"banana": "banana",
"orange": "laranja",
"grape": "uva",
"watermelon": "melancia",
"strawberry": "morango",
"cherry": "cereja",
"pineapple": "abacaxi",
"mango": "manga",
"lemon": "limão",
"peach": "pêssego",
"pear": "pera",
"plum": "ameixa",
"apricot": "damasco",
"blueberry": "mirtilo",
"raspberry": "framboesa",
"blackberry": "amora",
"coconut": "coco",
"kiwi": "kiwi",
"papaya": "mamão",
"fig": "figo",
"grapefruit": "toranja",
"lime": "lima",
"nectarine": "nectarina",
"pomegranate": "romã",
"tangerine": "tangerina",
"date": "tâmara",
"passionfruit": "maracujá",
"cantaloupe": "melão cantalupo",
"honeydew": "melão",
"carrot": "cenoura",
"potato": "batata",
"onion": "cebola",
"garlic": "alho",
"lettuce": "alface",
"cabbage": "repolho",
"spinach": "espinafre",
"broccoli": "brócolis",
"cauliflower": "couve-flor",
"tomato": "tomate",
"cucumber": "pepino",
"pepper": "pimentão",
"zucchini": "abobrinha",
"eggplant": "berinjela",
"pumpkin": "abóbora",
"corn": "milho",
"pea": "ervilha",
"bean": "feijão",
"rice": "arroz",
"bread": "pão",
"butter": "manteiga",
"cheese": "queijo",
"milk": "leite",
"yogurt": "iogurte",
"egg": "ovo",
"meat": "carne",
"chicken": "frango",
"beef": "carne bovina",
"pork": "carne de porco",
"fish": "peixe",
"shrimp": "camarão",
"crab": "caranguejo",
"lobster": "lagosta",
"salmon": "salmão",
"tuna": "atum",
"sausage": "linguiça",
"bacon": "bacon",
"ham": "presunto",
"turkey": "peru",
"sugar": "açúcar",
"salt": "sal",
"pepper spice": "pimenta",
"oil": "óleo",
"vinegar": "vinagre",
"ketchup": "ketchup",
"mustard": "mostarda",
"mayonnaise": "maionese",
"honey": "mel",
"jam": "geleia",
"chocolate": "chocolate",
"candy": "doce",
"cake": "bolo",
"pie": "torta",
"cookie": "biscoito",
"ice cream": "sorvete",
"juice": "suco",
"soda": "refrigerante",
"coffee": "café",
"tea": "chá",
"wine": "vinho",
"beer": "cerveja",
"water": "água",
"soup": "sopa",
"sandwich": "sanduíche",
"pizza": "pizza",
"pasta": "massa",
"noodle": "macarrão",
"rice dish": "prato de arroz",
"steak": "bife",
"hamburger": "hambúrguer",
"hotdog": "cachorro-quente",
"breakfast": "café da manhã",
"lunch": "almoço",
"dinner": "jantar",
"snack": "lanche",
"meal": "refeição",
"fork": "garfo",
"knife": "faca",
"spoon": "colher",
"plate": "prato",
"glass": "copo",
"cup": "xícara",
"bowl": "tigela",
"napkin": "guardanapo",
"straw": "canudo",
"table": "mesa",
"chair": "cadeira",
"kitchen": "cozinha",
"stove": "fogão",
"oven": "forno",
"microwave": "micro-ondas",
"refrigerator": "geladeira",
"freezer": "congelador",
"sink": "pia",
"dishwasher": "lava-louças",
"pan": "panela",
"pot": "caçarola",
"frying pan": "frigideira",
"cutting board": "tábua de corte",
"knife set": "conjunto de facas",
"blender": "liquidificador",
"toaster": "torradeira",
"mixer": "batedeira",
"grater": "ralador",
"peeler": "descascador",
"colander": "escorredor",
"measuring cup": "copo medidor",
"measuring spoon": "colher medidora",
"timer": "cronômetro",
"recipe": "receita",
"ingredient": "ingrediente",
"flour": "farinha",
"yeast": "fermento",
"baking powder": "fermento em pó",
"baking soda": "bicarbonato de sódio",
"cinnamon": "canela",
"vanilla": "baunilha",
"cocoa": "cacau",
"almond": "amêndoa",
"walnut": "noz",
"peanut": "amendoim",
"cashew": "castanha de caju",
"hazelnut": "avelã",
"pistachio": "pistache",
"sunflower seed": "semente de girassol",
"chia": "chia",
"flax": "linhaça",
"oat": "aveia",
"barley": "cevada",
"wheat": "trigo",
"cornmeal": "fubá",
"soy": "soja",
"tofu": "tofu",
"tempeh": "tempeh",
"seaweed": "alga",
"mushroom": "cogumelo",
"truffle": "trufa",
"syrup": "xarope",
"molasses": "melaço",
"cream": "creme",
"whipped cream": "chantilly",
"custard": "creme de confeiteiro",
"pudding": "pudim",
"gelatin": "gelatina",
"popsicle": "picolé",
"snack bar": "barrinha",
"granola": "granola",
"cereal": "cereal",
"cracker": "bolacha salgada",
"dough": "massa crua",
"batter": "massa líquida",
"pastry": "massa folhada",
"croissant": "croissant",
"bagel": "bagel",
"toast": "torrada",
"donut": "rosquinha",
"waffle": "waffle",
"pancake": "panqueca",
"scone": "scone"
}

while True:

    print("\n\n!------------------------------------------------! DICIONÁRIO !------------------------------------------------! ")
    print("Digite 1 para saber a tradução, 2 para adicionar um palavra e sua tradução, 3 para encerrar")
    ação = int(input("Qual função deseja executar: "))

    if ação == 1:
        palavra = input("Qual palavra em inglês gostaria de saber a tradução: ").lower()
        if palavra in dicionario:
            print(dicionario[palavra])
        else:
            print("!!ERRO, PALAVRA NÃO ENCONTRADA!!")
    
    elif ação == 2:
        palavranova = input("Digite a nova palavra: ").lower()
        traducaonova = input("Digite a tradução dela: ").lower()
        
        dicionario[palavranova] = traducaonova

    elif ação == 3:
        print("------- Bye =) -------")
        break

    else:
        print("\n\nCOMANDO INVÁLIDO!")




